Mine:     
super complicated...

In [1]:
path='C:\\Users\Luo_L\Desktop\Python Examples/rosalind_cons.txt'
f=open(path).read()
f1=f.replace('\n','')
f2=f1.split('>')
f2

['',
 'Rosalind_3172TCATGTTTTGCAGGGTCACCCGCATGGTCTCTCTAACATGGATGGTGACATTGCATCGCCACTTTCTGCCTGGCACAGTCGGTCCGAACTCAGCTTGCGCGCTACTTAGCGTCCACGCTACATAATCATCCTAGACGAGTCTGGGTCCATCTAACACACTTGTAGGTAATATAGTTAATCTGGCCCTCTTTTAGCGTGCTCCATTTCGCCTATGGTTCGGTAAGCATTCAATTAAAGGTTTTGCATGCGCAGTTATTGGGTGCCTAGAGTACGGGAACCAGGCCTTGTTACGGACCCTCAGTGGTACACGTGATGCCTCGTTCAGACGCCATCTGAAAAGATGCCATGTCTTTGAGAAGCTAGCGGGCAGGAACCTGTCCGTATTTTTTCTTAGTACATAGCGTCTCTGCTCCTTTTTCCCACTGGGCACTCTACCAGACCATATCCGGGGAAGTGGGCTAGGCCAGGTCTTATTAAATCACTCGCCGTAAACAAAAGGCACTGCCGTGGCTGGTGCTCCGACGCGTTCGCGCCCCCAGCGTTGAACGTCTCTTTCAACACAGCTGATGTTGATGCTAATCAGGTACCCGCCCACCATGTGTGTTATCGTAAACAATTTTGACATCCCCTACTTTGCTGGGGTATCGCATAAATATGATTTAGGCTTCCCGTTCCATTTTTTGAGCACCTCGTGAACAACTTGTACAATATACGCCAGAGCCGAAGATGCGCTGGAGCATTAAGCGAATAAATTGATACTAATCAGCCCTACCTACAATTCTGGAATGGGGAAGCCGGTGTCCCTCAACGTCCTTAGTCTTTTTGATTGGCCAGACCCTACTTACATCAATTGGACAAGGACTTAGTTCCTAACCTTGGCAAAGAATGCGTTTCTTTAATGGGGTGAGTTAACATAGTTCAGAGGGAATGGATAAGGAGCTTTAAGGCATTTTGCGATAGAACTTCCGACTAACC',
 '

In [2]:
fx=[]
for xx in f2[1:]:
    ff=xx[13:]
    fx.append(ff)
fx

['TCATGTTTTGCAGGGTCACCCGCATGGTCTCTCTAACATGGATGGTGACATTGCATCGCCACTTTCTGCCTGGCACAGTCGGTCCGAACTCAGCTTGCGCGCTACTTAGCGTCCACGCTACATAATCATCCTAGACGAGTCTGGGTCCATCTAACACACTTGTAGGTAATATAGTTAATCTGGCCCTCTTTTAGCGTGCTCCATTTCGCCTATGGTTCGGTAAGCATTCAATTAAAGGTTTTGCATGCGCAGTTATTGGGTGCCTAGAGTACGGGAACCAGGCCTTGTTACGGACCCTCAGTGGTACACGTGATGCCTCGTTCAGACGCCATCTGAAAAGATGCCATGTCTTTGAGAAGCTAGCGGGCAGGAACCTGTCCGTATTTTTTCTTAGTACATAGCGTCTCTGCTCCTTTTTCCCACTGGGCACTCTACCAGACCATATCCGGGGAAGTGGGCTAGGCCAGGTCTTATTAAATCACTCGCCGTAAACAAAAGGCACTGCCGTGGCTGGTGCTCCGACGCGTTCGCGCCCCCAGCGTTGAACGTCTCTTTCAACACAGCTGATGTTGATGCTAATCAGGTACCCGCCCACCATGTGTGTTATCGTAAACAATTTTGACATCCCCTACTTTGCTGGGGTATCGCATAAATATGATTTAGGCTTCCCGTTCCATTTTTTGAGCACCTCGTGAACAACTTGTACAATATACGCCAGAGCCGAAGATGCGCTGGAGCATTAAGCGAATAAATTGATACTAATCAGCCCTACCTACAATTCTGGAATGGGGAAGCCGGTGTCCCTCAACGTCCTTAGTCTTTTTGATTGGCCAGACCCTACTTACATCAATTGGACAAGGACTTAGTTCCTAACCTTGGCAAAGAATGCGTTTCTTTAATGGGGTGAGTTAACATAGTTCAGAGGGAATGGATAAGGAGCTTTAAGGCATTTTGCGATAGAACTTCCGACTAACC',
 'TATCGGCAAGTAATCCCT

In [49]:
fy=[]
for y in fx:
    fy.append(list(y))
fy
#往下翻，可以通过np.array来实现

[['T',
  'C',
  'A',
  'T',
  'G',
  'T',
  'T',
  'T',
  'T',
  'G',
  'C',
  'A',
  'G',
  'G',
  'G',
  'T',
  'C',
  'A',
  'C',
  'C',
  'C',
  'G',
  'C',
  'A',
  'T',
  'G',
  'G',
  'T',
  'C',
  'T',
  'C',
  'T',
  'C',
  'T',
  'A',
  'A',
  'C',
  'A',
  'T',
  'G',
  'G',
  'A',
  'T',
  'G',
  'G',
  'T',
  'G',
  'A',
  'C',
  'A',
  'T',
  'T',
  'G',
  'C',
  'A',
  'T',
  'C',
  'G',
  'C',
  'C',
  'A',
  'C',
  'T',
  'T',
  'T',
  'C',
  'T',
  'G',
  'C',
  'C',
  'T',
  'G',
  'G',
  'C',
  'A',
  'C',
  'A',
  'G',
  'T',
  'C',
  'G',
  'G',
  'T',
  'C',
  'C',
  'G',
  'A',
  'A',
  'C',
  'T',
  'C',
  'A',
  'G',
  'C',
  'T',
  'T',
  'G',
  'C',
  'G',
  'C',
  'G',
  'C',
  'T',
  'A',
  'C',
  'T',
  'T',
  'A',
  'G',
  'C',
  'G',
  'T',
  'C',
  'C',
  'A',
  'C',
  'G',
  'C',
  'T',
  'A',
  'C',
  'A',
  'T',
  'A',
  'A',
  'T',
  'C',
  'A',
  'T',
  'C',
  'C',
  'T',
  'A',
  'G',
  'A',
  'C',
  'G',
  'A',
  'G',
  'T',
  'C',
  'T',
  'G',

In [4]:
lenth=len(fy[0])

In [5]:
cA=[]
cC=[]
cG=[]
cT=[]
for n in range(0,lenth):
    columnA=0
    columnC=0
    columnG=0
    columnT=0
    for x in fy:
        if x[n]=='A':
            columnA+=1
        elif x[n]=='C':
            columnC+=1        
        elif x[n]=='G':
            columnG+=1
        elif x[n]=='T':
            columnT+=1
    cA.append(columnA)
    cC.append(columnC)
    cG.append(columnG)
    cT.append(columnT)

In [80]:
Dict=dict(zip(['A','C','G','T'],[cA,cC,cG,cT]))
Dict

{'A': [2,
  4,
  5,
  1,
  3,
  2,
  1,
  2,
  3,
  3,
  1,
  3,
  2,
  1,
  2,
  2,
  1,
  1,
  0,
  4,
  3,
  2,
  3,
  5,
  0,
  4,
  1,
  4,
  2,
  3,
  3,
  0,
  1,
  2,
  2,
  3,
  0,
  5,
  1,
  1,
  3,
  3,
  1,
  2,
  3,
  3,
  4,
  3,
  1,
  2,
  4,
  2,
  1,
  1,
  1,
  3,
  3,
  3,
  3,
  3,
  2,
  2,
  3,
  1,
  3,
  3,
  2,
  1,
  3,
  2,
  3,
  2,
  4,
  2,
  5,
  2,
  3,
  0,
  1,
  4,
  0,
  2,
  6,
  4,
  2,
  1,
  3,
  4,
  3,
  2,
  4,
  4,
  3,
  3,
  3,
  1,
  1,
  4,
  6,
  3,
  1,
  3,
  3,
  2,
  2,
  2,
  2,
  5,
  4,
  0,
  4,
  4,
  3,
  3,
  5,
  3,
  1,
  1,
  0,
  1,
  2,
  4,
  1,
  6,
  1,
  3,
  1,
  6,
  4,
  3,
  4,
  0,
  4,
  4,
  5,
  3,
  1,
  6,
  2,
  1,
  0,
  1,
  3,
  0,
  4,
  0,
  3,
  4,
  3,
  3,
  2,
  2,
  4,
  2,
  3,
  3,
  2,
  4,
  3,
  0,
  1,
  3,
  0,
  5,
  3,
  0,
  1,
  2,
  4,
  4,
  2,
  4,
  3,
  2,
  1,
  2,
  2,
  3,
  3,
  3,
  3,
  2,
  0,
  2,
  1,
  3,
  2,
  2,
  5,
  1,
  3,
  3,
  2,
  3,
  2,
  4,
  4,
  4,
  2,


In [46]:
List=[]
for N in range(0,len(Dict['A'])):
    if Dict['A'][N]==max(Dict['A'][N],Dict['C'][N],Dict['G'][N],Dict['T'][N]):
        List.append('A')
    elif Dict['C'][N]==max(Dict['A'][N],Dict['C'][N],Dict['G'][N],Dict['T'][N]):
        List.append('C')
    elif Dict['G'][N]==max(Dict['A'][N],Dict['C'][N],Dict['G'][N],Dict['T'][N]):
        List.append('G')
    elif Dict['T'][N]==max(Dict['A'][N],Dict['C'][N],Dict['G'][N],Dict['T'][N]):
        List.append('T')
List

['T',
 'A',
 'A',
 'T',
 'A',
 'T',
 'T',
 'G',
 'A',
 'A',
 'T',
 'T',
 'G',
 'C',
 'C',
 'T',
 'T',
 'C',
 'G',
 'A',
 'C',
 'G',
 'A',
 'A',
 'C',
 'A',
 'G',
 'A',
 'T',
 'G',
 'A',
 'T',
 'C',
 'G',
 'T',
 'A',
 'G',
 'A',
 'T',
 'G',
 'A',
 'A',
 'T',
 'T',
 'G',
 'T',
 'A',
 'A',
 'T',
 'C',
 'A',
 'G',
 'G',
 'C',
 'T',
 'A',
 'C',
 'G',
 'A',
 'G',
 'G',
 'C',
 'A',
 'C',
 'A',
 'A',
 'T',
 'C',
 'A',
 'C',
 'A',
 'G',
 'A',
 'C',
 'A',
 'C',
 'A',
 'G',
 'C',
 'A',
 'C',
 'T',
 'A',
 'A',
 'C',
 'G',
 'A',
 'A',
 'T',
 'G',
 'A',
 'A',
 'T',
 'A',
 'G',
 'T',
 'C',
 'A',
 'A',
 'T',
 'C',
 'A',
 'C',
 'C',
 'C',
 'T',
 'T',
 'A',
 'A',
 'C',
 'A',
 'A',
 'A',
 'A',
 'A',
 'T',
 'G',
 'C',
 'G',
 'G',
 'C',
 'A',
 'T',
 'A',
 'G',
 'A',
 'T',
 'A',
 'A',
 'A',
 'A',
 'T',
 'A',
 'A',
 'A',
 'A',
 'G',
 'A',
 'G',
 'T',
 'C',
 'G',
 'A',
 'G',
 'A',
 'C',
 'T',
 'A',
 'A',
 'C',
 'C',
 'T',
 'A',
 'C',
 'A',
 'A',
 'G',
 'A',
 'A',
 'C',
 'C',
 'A',
 'C',
 'A',
 'A',
 'C',
 'T'

In [87]:
for z in List:
    print(z,end='')
for nn in 'ACGT':
    print('\n'+nn+': ',end='')
    for zz in Dict[nn]:
        print(zz,end=' ')
#把数字list去逗号打印的更简便方法：往下翻，map(str,某list)

TAATATTGAATTGCCTTCGACGAACAGATGATCGTAGATGAATTGTAATCAGGCTACGAGGCACAATCACAGACACAGCACTAACGAATGAATAGTCAATCACCCTTAACAAAAATGCGGCATAGATAAAATAAAAGAGTCGAGACTAACCTACAAGAACCACAACTTAACAAGCGGAAAAGCTCTCCACCGCCGAAACTCTCTGAGAAGGATGAATTGGCTAGAAATTAGGTATAGGTTGCGGGGGAGGACCAAGTCCGGAGCGATGTGACGACCGTCCAACTGTGTAGATTGCCCTCAATCAGCCTATTGAACCACCCTAGAGAAGCAGCAGGCAGGAACATCCCATCCAAGCGAACTTGCCGAGTTTACGACGCGCCTTACTTAACGTTAGCAAAGCACGTTCGACCTTATTCCCGCTCGGATGCAACCAACATAGCAATACGTAAGCAACACGGCACGGAATCTGCCGCTTCCAGCACCCGGCACATCAAAGGGCCGGCTGCACGTTACCGGGACTCAGCACGCCGATTCAACGCATTACAAATTCATTGCCAAGAGGCGAGAGGTTCTGAGGTCAGCAGTAACAAGGAACTGTATCTTATAATCTCCAAAATGCGATGATCGCTCAAACTCCGCTACTATCGCAACAAGATGGACCAGAACTGCAGAAACATATGTAAATTTCCCCCAGCACAACCGATAATAAAATGAGAAGATGCGACACGGGCAGGCGAAAAGTATTGTCTAAACACCCCAAACACGCCTAAAGCCGCCGTTCGGCAAAGTCGAATAGCCTACGGCGACCAGAAATGCCTCATAAGGGCGAGACCACCCCCAGGGTCAGCAATTACAAGAACGCTTACTTACCCTAAAATAAAAAGAAGACGGGCAGGCATAGACAATGGAGTTGGGAATTCCGTGGACACGAGTCAGCATTTTGGACGAAGATCGACAGCAGAGCAACGAGGGACG
A: 2 4 5 1 3 2 1 2 3 3 1

Rosalind1:     
结合np.array + argmax + enumerate +map 都是我的弱项！

In [86]:
import numpy as np
from numpy import array as arr

A = [arr(list(line.strip())) for line in fx]
A = arr(A)

genes = arr(list('ACGT'))
P = arr([(A == g).sum(axis=0) for g in genes])
c = genes[P.argmax(axis=0)]  ##上一行P按照g的顺序即'ACGT'的顺序排列，所以argmax所指的index也按如此顺序？
c = ''.join(c)

print (c)
for i, g in enumerate(genes): 
    print( '%s:' % g, ' '.join(map(str, P[i]))) #把数字list去逗号打印的更简便方法

TAATATTGAATTGCCTTCGACGAACAGATGATCGTAGATGAATTGTAATCAGGCTACGAGGCACAATCACAGACACAGCACTAACGAATGAATAGTCAATCACCCTTAACAAAAATGCGGCATAGATAAAATAAAAGAGTCGAGACTAACCTACAAGAACCACAACTTAACAAGCGGAAAAGCTCTCCACCGCCGAAACTCTCTGAGAAGGATGAATTGGCTAGAAATTAGGTATAGGTTGCGGGGGAGGACCAAGTCCGGAGCGATGTGACGACCGTCCAACTGTGTAGATTGCCCTCAATCAGCCTATTGAACCACCCTAGAGAAGCAGCAGGCAGGAACATCCCATCCAAGCGAACTTGCCGAGTTTACGACGCGCCTTACTTAACGTTAGCAAAGCACGTTCGACCTTATTCCCGCTCGGATGCAACCAACATAGCAATACGTAAGCAACACGGCACGGAATCTGCCGCTTCCAGCACCCGGCACATCAAAGGGCCGGCTGCACGTTACCGGGACTCAGCACGCCGATTCAACGCATTACAAATTCATTGCCAAGAGGCGAGAGGTTCTGAGGTCAGCAGTAACAAGGAACTGTATCTTATAATCTCCAAAATGCGATGATCGCTCAAACTCCGCTACTATCGCAACAAGATGGACCAGAACTGCAGAAACATATGTAAATTTCCCCCAGCACAACCGATAATAAAATGAGAAGATGCGACACGGGCAGGCGAAAAGTATTGTCTAAACACCCCAAACACGCCTAAAGCCGCCGTTCGGCAAAGTCGAATAGCCTACGGCGACCAGAAATGCCTCATAAGGGCGAGACCACCCCCAGGGTCAGCAATTACAAGAACGCTTACTTACCCTAAAATAAAAAGAAGACGGGCAGGCATAGACAATGGAGTTGGGAATTCCGTGGACACGAGTCAGCATTTTGGACGAAGATCGACAGCAGAGCAACGAGGGACG
A: 2 4 5 1 3 2 1 2 3 3 1

练习与验证：

In [48]:
arr(fy)==arr(A)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [54]:
arr(A)

array([['T', 'C', 'A', ..., 'A', 'C', 'C'],
       ['T', 'A', 'T', ..., 'T', 'C', 'G'],
       ['G', 'A', 'T', ..., 'G', 'G', 'G'],
       ...,
       ['T', 'T', 'C', ..., 'A', 'G', 'T'],
       ['T', 'G', 'A', ..., 'A', 'C', 'G'],
       ['C', 'T', 'C', ..., 'A', 'A', 'A']], dtype='<U1')

In [51]:
arr(list('ACGT'))

array(['A', 'C', 'G', 'T'], dtype='<U1')

In [65]:
(A=='A').sum(axis=0)

array([2, 4, 5, 1, 3, 2, 1, 2, 3, 3, 1, 3, 2, 1, 2, 2, 1, 1, 0, 4, 3, 2,
       3, 5, 0, 4, 1, 4, 2, 3, 3, 0, 1, 2, 2, 3, 0, 5, 1, 1, 3, 3, 1, 2,
       3, 3, 4, 3, 1, 2, 4, 2, 1, 1, 1, 3, 3, 3, 3, 3, 2, 2, 3, 1, 3, 3,
       2, 1, 3, 2, 3, 2, 4, 2, 5, 2, 3, 0, 1, 4, 0, 2, 6, 4, 2, 1, 3, 4,
       3, 2, 4, 4, 3, 3, 3, 1, 1, 4, 6, 3, 1, 3, 3, 2, 2, 2, 2, 5, 4, 0,
       4, 4, 3, 3, 5, 3, 1, 1, 0, 1, 2, 4, 1, 6, 1, 3, 1, 6, 4, 3, 4, 0,
       4, 4, 5, 3, 1, 6, 2, 1, 0, 1, 3, 0, 4, 0, 3, 4, 3, 3, 2, 2, 4, 2,
       3, 3, 2, 4, 3, 0, 1, 3, 0, 5, 3, 0, 1, 2, 4, 4, 2, 4, 3, 2, 1, 2,
       2, 3, 3, 3, 3, 2, 0, 2, 1, 3, 2, 2, 5, 1, 3, 3, 2, 3, 2, 4, 4, 4,
       2, 2, 1, 2, 3, 1, 2, 3, 1, 4, 3, 2, 1, 5, 4, 3, 4, 4, 2, 2, 0, 0,
       2, 3, 6, 1, 4, 6, 4, 1, 1, 4, 3, 2, 1, 3, 1, 4, 1, 2, 1, 0, 1, 1,
       2, 2, 3, 1, 2, 6, 2, 1, 5, 3, 2, 3, 7, 1, 3, 0, 3, 2, 0, 4, 1, 1,
       2, 6, 2, 3, 0, 3, 4, 0, 2, 4, 1, 1, 1, 2, 2, 3, 4, 3, 1, 2, 3, 2,
       1, 2, 4, 3, 3, 1, 3, 3, 1, 2, 2, 1, 3, 3, 3,

In [66]:
P

array([[2, 4, 5, ..., 4, 2, 2],
       [3, 2, 2, ..., 2, 5, 2],
       [1, 1, 1, ..., 2, 2, 4],
       [4, 3, 2, ..., 2, 1, 2]])

In [70]:
P.argmax(axis=0)

array([3, 0, 0, 3, 0, 3, 3, 2, 0, 0, 3, 3, 2, 1, 1, 3, 3, 1, 2, 0, 1, 2,
       0, 0, 1, 0, 2, 0, 3, 2, 0, 3, 1, 2, 3, 0, 2, 0, 3, 2, 0, 0, 3, 3,
       2, 3, 0, 0, 3, 1, 0, 2, 2, 1, 3, 0, 1, 2, 0, 2, 2, 1, 0, 1, 0, 0,
       3, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 2, 1, 0, 1, 3, 0, 0, 1, 2, 0, 0,
       3, 2, 0, 0, 3, 0, 2, 3, 1, 0, 0, 3, 1, 0, 1, 1, 1, 3, 3, 0, 0, 1,
       0, 0, 0, 0, 0, 3, 2, 1, 2, 2, 1, 0, 3, 0, 2, 0, 3, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 2, 0, 2, 3, 1, 2, 0, 2, 0, 1, 3, 0, 0, 1, 1, 3, 0, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1, 3, 3, 0, 0, 1, 0, 0, 2, 1, 2,
       2, 0, 0, 0, 0, 2, 1, 3, 1, 3, 1, 1, 0, 1, 1, 2, 1, 1, 2, 0, 0, 0,
       1, 3, 1, 3, 1, 3, 2, 0, 2, 0, 0, 2, 2, 0, 3, 2, 0, 0, 3, 3, 2, 2,
       1, 3, 0, 2, 0, 0, 0, 3, 3, 0, 2, 2, 3, 0, 3, 0, 2, 2, 3, 3, 2, 1,
       2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 1, 0, 0, 2, 3, 1, 1, 2, 2, 0, 2, 1,
       2, 0, 3, 2, 3, 2, 0, 1, 2, 0, 1, 1, 2, 3, 1, 1, 0, 0, 1, 3, 2, 3,
       2, 3, 0, 2, 0, 3, 3, 2, 1, 1, 1, 3, 1, 0, 0,

In [78]:
"".join(genes[P.argmax(axis=0)])

'TAATATTGAATTGCCTTCGACGAACAGATGATCGTAGATGAATTGTAATCAGGCTACGAGGCACAATCACAGACACAGCACTAACGAATGAATAGTCAATCACCCTTAACAAAAATGCGGCATAGATAAAATAAAAGAGTCGAGACTAACCTACAAGAACCACAACTTAACAAGCGGAAAAGCTCTCCACCGCCGAAACTCTCTGAGAAGGATGAATTGGCTAGAAATTAGGTATAGGTTGCGGGGGAGGACCAAGTCCGGAGCGATGTGACGACCGTCCAACTGTGTAGATTGCCCTCAATCAGCCTATTGAACCACCCTAGAGAAGCAGCAGGCAGGAACATCCCATCCAAGCGAACTTGCCGAGTTTACGACGCGCCTTACTTAACGTTAGCAAAGCACGTTCGACCTTATTCCCGCTCGGATGCAACCAACATAGCAATACGTAAGCAACACGGCACGGAATCTGCCGCTTCCAGCACCCGGCACATCAAAGGGCCGGCTGCACGTTACCGGGACTCAGCACGCCGATTCAACGCATTACAAATTCATTGCCAAGAGGCGAGAGGTTCTGAGGTCAGCAGTAACAAGGAACTGTATCTTATAATCTCCAAAATGCGATGATCGCTCAAACTCCGCTACTATCGCAACAAGATGGACCAGAACTGCAGAAACATATGTAAATTTCCCCCAGCACAACCGATAATAAAATGAGAAGATGCGACACGGGCAGGCGAAAAGTATTGTCTAAACACCCCAAACACGCCTAAAGCCGCCGTTCGGCAAAGTCGAATAGCCTACGGCGACCAGAAATGCCTCATAAGGGCGAGACCACCCCCAGGGTCAGCAATTACAAGAACGCTTACTTACCCTAAAATAAAAAGAAGACGGGCAGGCATAGACAATGGAGTTGGGAATTCCGTGGACACGAGTCAGCATTTTGGACGAAGATCGACAGCAGAGCAACGAGGGACG'

In [85]:
' '.join(map(str,Dict['A']))

'2 4 5 1 3 2 1 2 3 3 1 3 2 1 2 2 1 1 0 4 3 2 3 5 0 4 1 4 2 3 3 0 1 2 2 3 0 5 1 1 3 3 1 2 3 3 4 3 1 2 4 2 1 1 1 3 3 3 3 3 2 2 3 1 3 3 2 1 3 2 3 2 4 2 5 2 3 0 1 4 0 2 6 4 2 1 3 4 3 2 4 4 3 3 3 1 1 4 6 3 1 3 3 2 2 2 2 5 4 0 4 4 3 3 5 3 1 1 0 1 2 4 1 6 1 3 1 6 4 3 4 0 4 4 5 3 1 6 2 1 0 1 3 0 4 0 3 4 3 3 2 2 4 2 3 3 2 4 3 0 1 3 0 5 3 0 1 2 4 4 2 4 3 2 1 2 2 3 3 3 3 2 0 2 1 3 2 2 5 1 3 3 2 3 2 4 4 4 2 2 1 2 3 1 2 3 1 4 3 2 1 5 4 3 4 4 2 2 0 0 2 3 6 1 4 6 4 1 1 4 3 2 1 3 1 4 1 2 1 0 1 1 2 2 3 1 2 6 2 1 5 3 2 3 7 1 3 0 3 2 0 4 1 1 2 6 2 3 0 3 4 0 2 4 1 1 1 2 2 3 4 3 1 2 3 2 1 2 4 3 3 1 3 3 1 2 2 1 3 3 3 3 0 3 2 2 0 2 4 2 3 2 4 3 1 2 3 2 1 2 0 3 0 6 4 3 3 3 1 4 2 2 4 2 2 2 4 3 2 4 4 2 4 1 1 2 3 3 1 1 2 4 3 2 2 2 5 4 2 2 2 2 0 1 1 3 1 2 3 2 4 2 4 4 1 1 1 2 1 2 1 1 6 2 2 2 3 3 2 3 3 2 3 4 2 4 3 5 1 4 4 2 1 2 1 2 3 5 2 2 0 2 4 2 2 2 0 1 3 1 3 1 2 1 4 2 1 2 3 4 2 3 3 5 1 5 1 4 2 1 4 5 2 4 3 1 2 4 5 3 2 3 5 3 3 2 2 1 2 3 2 2 0 6 5 2 2 2 2 2 2 2 2 0 1 2 1 4 2 2 4 2 2 3 1 3 1 4 1 7 3 2 4 5 5 2 2 1 1 3

In [94]:
for i, g in enumerate(genes): 
    print( 'g:', ' '.join(map(str, P[i])))  #所以要用%s代替g

g: 2 4 5 1 3 2 1 2 3 3 1 3 2 1 2 2 1 1 0 4 3 2 3 5 0 4 1 4 2 3 3 0 1 2 2 3 0 5 1 1 3 3 1 2 3 3 4 3 1 2 4 2 1 1 1 3 3 3 3 3 2 2 3 1 3 3 2 1 3 2 3 2 4 2 5 2 3 0 1 4 0 2 6 4 2 1 3 4 3 2 4 4 3 3 3 1 1 4 6 3 1 3 3 2 2 2 2 5 4 0 4 4 3 3 5 3 1 1 0 1 2 4 1 6 1 3 1 6 4 3 4 0 4 4 5 3 1 6 2 1 0 1 3 0 4 0 3 4 3 3 2 2 4 2 3 3 2 4 3 0 1 3 0 5 3 0 1 2 4 4 2 4 3 2 1 2 2 3 3 3 3 2 0 2 1 3 2 2 5 1 3 3 2 3 2 4 4 4 2 2 1 2 3 1 2 3 1 4 3 2 1 5 4 3 4 4 2 2 0 0 2 3 6 1 4 6 4 1 1 4 3 2 1 3 1 4 1 2 1 0 1 1 2 2 3 1 2 6 2 1 5 3 2 3 7 1 3 0 3 2 0 4 1 1 2 6 2 3 0 3 4 0 2 4 1 1 1 2 2 3 4 3 1 2 3 2 1 2 4 3 3 1 3 3 1 2 2 1 3 3 3 3 0 3 2 2 0 2 4 2 3 2 4 3 1 2 3 2 1 2 0 3 0 6 4 3 3 3 1 4 2 2 4 2 2 2 4 3 2 4 4 2 4 1 1 2 3 3 1 1 2 4 3 2 2 2 5 4 2 2 2 2 0 1 1 3 1 2 3 2 4 2 4 4 1 1 1 2 1 2 1 1 6 2 2 2 3 3 2 3 3 2 3 4 2 4 3 5 1 4 4 2 1 2 1 2 3 5 2 2 0 2 4 2 2 2 0 1 3 1 3 1 2 1 4 2 1 2 3 4 2 3 3 5 1 5 1 4 2 1 4 5 2 4 3 1 2 4 5 3 2 3 5 3 3 2 2 1 2 3 2 2 0 6 5 2 2 2 2 2 2 2 2 0 1 2 1 4 2 2 4 2 2 3 1 3 1 4 1 7 3 2 4 5 5 2 2 1 1